import {
  C,
  S,
  P,
  R,
  H,
  culture,
  rare,
  type LivingEntry,
} from "./living-expansion-tools";

/** Collector numbers 25–80: voluntary service, practical care and contested debt. */
export const termsOfShelterExpansion: LivingEntry[] = [
  ...culture("Oath", [
    C(
      "Unbound Gate Volunteer",
      "dawn",
      1,
      2,
      1,
      "A human volunteer in reused plate opens a wagon-court gate, the cut ends of an old service cord tied to neither wrist.",
      { keywords: ["vigilance"] },
    ),
    C(
      "Empty-bedroll Keeper",
      "grave",
      2,
      2,
      2,
      "A human veteran folds an absent companion's bedroll beside a quiet wheel, keeping their worn pewter cup apart from the pay chest.",
      { trigger: "mourning" },
    ),
    C(
      "Civilian Yard Defender",
      "dawn",
      3,
      3,
      3,
      "A human repairer braces a broad workshop door with a salvaged shield while civilian families finish loading the carts.",
      { keywords: ["rootfast"] },
    ),
    C(
      "Roadside Muster Caller",
      "grave",
      4,
      4,
      3,
      "A human messenger holds an open roll case beside a road camp, offering a returning veteran a place without an inherited seal.",
      { effect: "recall", amount: 1 },
    ),
    S(
      "Take the Willing Watch",
      "Instant",
      "dawn",
      1,
      "renew",
      1,
      "A fresh human guard accepts a lantern from a seated veteran; the old oath tablet remains wrapped and out of reach.",
    ),
    S(
      "Offer Another Contract",
      "Sorcery",
      "grave",
      2,
      "recall",
      1,
      "An open roll case and an unfastened pewter clasp wait on a wagon step beside a returned travel pack.",
    ),
    P(
      "Field Repair Jack",
      "Artifact",
      "dawn",
      2,
      "mana-rock",
      "A reused iron screw jack raises one wagon axle over a canvas tool roll in the civilian repair yard.",
    ),
    C(
      "Family Pay Delegate",
      "dawn",
      2,
      2,
      3,
      "A human household delegate sets a plain cooking bowl beside the campaign pay chest, insisting that another voice be heard.",
      { trigger: "welcome" },
    ),
    C(
      "Scarred Escort Veteran",
      "grave",
      3,
      3,
      2,
      "A human veteran with a scarred cheek stands at a narrow road cut, a practical spear held low beside patched vermilion sleeves.",
      { keywords: ["deathtouch"] },
    ),
    C(
      "Wagon-circle Marshal",
      "dawn",
      4,
      4,
      4,
      "An unnamed human marshal plants a long hooked staff between two wagons while the families behind her keep their own household signs.",
      { keywords: ["vigilance", "reach"] },
    ),
    S(
      "Collect the Withheld Pay",
      "Instant",
      "grave",
      2,
      "drain",
      2,
      "A collector's imagined dark thread pulls two loose coins from a closed officer's purse toward an empty household bowl.",
    ),
    S(
      "Hold the Common Yard",
      "Sorcery",
      "dawn",
      3,
      "rally",
      1,
      "Human repairers and off-duty escorts lift their ordinary tools together along the wagon court's breached fence.",
    ),
    P(
      "Accounts in Every Hand",
      "Enchantment",
      "grave",
      3,
      "recordwork",
      "Soft violet light joins separate roll cases around a repaired worktable, with each household retaining its own clasp.",
    ),
    C(
      "Unsealed Rearguard",
      "grave",
      5,
      5,
      4,
      "A human rear-guard captain strides back through windblown canvas to cover departing civilians, carrying a split seal on a plain chain.",
      { keywords: ["haste"], trigger: "mourning" },
    ),
    S(
      "Stand for the Departing",
      "Instant",
      "dawn",
      3,
      "pump",
      3,
      "Warm imagined light settles over one human escort's shield while the last wagon passes behind her into the dawn.",
    ),
    P(
      "The Open Muster Standard",
      "Artifact",
      "dawn",
      4,
      "anthem",
      "A faded vermilion standard hangs from a repaired wagon spar; its broken seal rests below an unknotted gathering cord.",
    ),
  ]),
  ...culture("Radiance", [
    C(
      "Clean-cup Attendant",
      "dawn",
      1,
      1,
      2,
      "A human attendant in plain linen offers a clean cup through an open hospice window beneath a shuttered beeswax lamp.",
      { keywords: ["lifelink"] },
    ),
    C(
      "Night Linen Carrier",
      "grave",
      2,
      2,
      3,
      "A human worker brings folded blue linen through a quiet care-house passage, keeping used cloth in a separate covered basket.",
      { effect: "heal", amount: 1 },
    ),
    C(
      "Open-court Host",
      "dawn",
      3,
      2,
      4,
      "A human host draws an extra chair into the ventilated hospice court as a road-worn family reaches the threshold.",
      { trigger: "welcome" },
    ),
    C(
      "Returning Supply Escort",
      "grave",
      4,
      3,
      4,
      "A human escort sets a recovered companion's travel kit beside fresh supply baskets at the hospice door.",
      { effect: "recall", amount: 1 },
    ),
    S(
      "Shelter the Shuttered Lamp",
      "Instant",
      "dawn",
      1,
      "shield",
      3,
      "A linen-clad hand closes one side of a beeswax lamp against driving rain while its light still reaches the refuge doorway.",
    ),
    S(
      "Replenish the Care Stores",
      "Sorcery",
      "dawn",
      2,
      "heal",
      6,
      "Clean jars, rolled linen and bread fill open wooden shelves in a bright care house; the service window remains unbarred.",
    ),
    P(
      "The Spare Resting Bench",
      "Artifact",
      "dawn",
      3,
      "welcome",
      "A scrubbed wooden bench with a folded blue blanket waits beneath a ventilated hospice awning beside an extra cup.",
    ),
    C(
      "Threshold Supply Guard",
      "grave",
      2,
      1,
      4,
      "A human guard in plain washed-blue clothing holds a short spear across a store-room approach, leaving the care entrance open.",
      { keywords: ["deathtouch"] },
    ),
    C(
      "Beeswax Vigil Attendant",
      "dawn",
      3,
      3,
      3,
      "A human attendant trims one steady lamp beside a resting traveler, with the night's used cloth carefully bundled away.",
      { trigger: "lifegain" },
    ),
    C(
      "Long-watch Caretaker",
      "grave",
      4,
      3,
      5,
      "An older human caretaker sits upright beside an open window, offering a warm bowl after the rest of the corridor has darkened.",
      { keywords: ["lifelink"] },
    ),
    S(
      "Steady the Supply Bearer",
      "Instant",
      "dawn",
      2,
      "pump",
      2,
      "A collector's soft gold light braces a human porter's shoulders as a full supply basket crosses a flooded hospice step.",
    ),
    S(
      "Break the Coerced Provision",
      "Sorcery",
      "grave",
      4,
      "drain",
      4,
      "In an imagined spell, a restrictive red cord loosens from a sealed provision jar and its glow returns toward a waiting refuge.",
    ),
    P(
      "Air Through Every Shutter",
      "Enchantment",
      "dawn",
      3,
      "sanctuary",
      "Pale light and moving linen trace open airways through a care court, with no bars or magical quarantine wall.",
    ),
    C(
      "Lantern Doorwarden",
      "dawn",
      5,
      4,
      6,
      "An unnamed human hospice warden holds an ordinary shield beside a wide-open door, keeping a small shuttered lamp raised for approaching guests.",
      { keywords: ["lifelink", "vigilance"] },
    ),
    S(
      "End the Predatory Watch",
      "Instant",
      "grave",
      4,
      "destroy",
      1,
      "An invented violet-and-gold spell collapses an armed extortionist's shadow outside a refuge gate while the open lantern stays lit.",
    ),
    P(
      "The Night Supply Ledger",
      "Artifact",
      "grave",
      4,
      "archive",
      "A plain stitched ledger, shuttered lamp and separate empty and filled supply jars sit on a worn hospice worktable.",
    ),
  ]),
  ...culture("Grave", [
    C(
      "Ancestral Door Retainer",
      "grave",
      1,
      1,
      3,
      "A living human retainer stands firmly at a Vesper household door, one hand resting on a long-used iron latch beneath folded evening cloth.",
      { keywords: ["rootfast"] },
    ),
    C(
      "Evening Meal Steward",
      "dawn",
      2,
      2,
      2,
      "A living human steward sets an ordinary supper before tired retainers in a quiet court service room, far from the patrons' formal table.",
      { effect: "heal", amount: 2 },
    ),
    C(
      "Measured-cup Patron",
      "grave",
      3,
      3,
      2,
      "An unnamed living vampiric patron with a composed, pale face studies a small covered cup beside a household debt case; no feeding is shown.",
      { keywords: ["lifelink"] },
    ),
    C(
      "Retainers' Hall Protector",
      "dawn",
      4,
      3,
      5,
      "A living human guard watches the servants' corridor from a plain chair, a practical shield beside the brocade reserved for the court.",
      { keywords: ["vigilance"] },
    ),
    S(
      "Invoke the Old Provision",
      "Instant",
      "grave",
      2,
      "drain",
      2,
      "A collector's imagined crimson filament links an ancestral seal to a covered silver cup in a dim household chamber.",
      { colored: 2 },
    ),
    S(
      "Revoke the Violent Claim",
      "Sorcery",
      "grave",
      3,
      "destroy",
      1,
      "An imagined dark spell shatters a coercive claimant's raised seal above a Vesper service stair, leaving the living retainers unharmed.",
    ),
    P(
      "Vesper Service Keyring",
      "Artifact",
      "grave",
      2,
      "mana-rock",
      "A ring of practical iron service keys lies on folded plum cloth beside a single old household seal.",
    ),
    C(
      "Departed-service Archivist",
      "grave",
      2,
      2,
      3,
      "A living human archivist ties a closed roll for a departed retainer, leaving an empty space among the household's old service cases.",
      { trigger: "mourning" },
    ),
    C(
      "Guest-wing Chamberlain",
      "dawn",
      3,
      2,
      5,
      "A living human chamberlain opens a quiet guest chamber with fresh linen and two separate places for unlike visiting households.",
      { trigger: "welcome" },
    ),
    C(
      "Blood-provision Assessor",
      "grave",
      4,
      4,
      3,
      "An unnamed living vampiric assessor examines sealed provision vessels across a formal desk from a standing human household representative.",
      { effect: "drain", amount: 2 },
    ),
    S(
      "Bar the Inherited Threat",
      "Instant",
      "dawn",
      3,
      "shield",
      7,
      "Warm imagined light settles into the heavy inner door of a retainers' hall while a threatening ancestral seal fades outside.",
    ),
    S(
      "Convene the Household Answer",
      "Sorcery",
      "dawn",
      4,
      "rally",
      2,
      "Living human retainers assemble with their own tools in the Vesper court's outer hall, leaving the patron's elevated seat empty.",
    ),
    P(
      "The Unanswered Summons",
      "Enchantment",
      "grave",
      3,
      "watchfire",
      "A dim crimson pulse travels from an unopened summons case toward a distant court window, suggesting an obligation still being contested.",
    ),
    C(
      "Patron of the Unquiet Ledger",
      "grave",
      6,
      5,
      6,
      "An unnamed living vampiric patron stands beside an open debt cabinet, elegant evening clothes contrasting with the plain household rolls within.",
      { keywords: ["lifelink", "daunt"] },
    ),
    S(
      "Call the Overdue Reckoning",
      "Instant",
      "grave",
      4,
      "drain",
      5,
      "A collector's crimson spell flows out of a rigid ancestral seal into several plain household bowls on the other side of the court table.",
    ),
    P(
      "Copies Beyond the Court",
      "Artifact",
      "dawn",
      4,
      "recordwork",
      "Matching unlettered roll cases rest on opposite sides of an open household gate, with the old court seal kept separate from both.",
    ),
  ]),
  R(
    "Morning Refuge Court",
    "dawn",
    ["dawn"],
    "common",
    "An empty ventilated refuge court receives gentle dawn through pale linen, with clean bowls and a low bench beside the open door.",
  ),
  R(
    "Lamplit Service Crossing",
    "dawn",
    ["dawn", "grave"],
    "uncommon",
    "A quiet road joins a care-house lamp to a distant evening court; a resting cart waits at the crossing before continuing.",
  ),
  R(
    "Wagon-smith Shelter",
    "dawn",
    ["dawn", "ember"],
    "rare",
    "A canvas-sided civilian repair shelter glows around a small practical forge, with dawn light on a safely propped wagon wheel.",
  ),
  R(
    "Rainwell Memorial Garden",
    "grave",
    ["grave", "tide"],
    "rare",
    "Rain collects in shallow stone bowls among a quiet garden's modest memorial markers; a covered path follows the blue-grey water.",
  ),
  rare(
    P(
      "The Unfastened Service Chest",
      "Artifact",
      "dawn",
      4,
      "welcome",
      "An invented collector comparison places separate company clasps, hospice linens and Vesper roll cases in an open chest with no shared binding seal.",
    ),
  ),
  rare(
    S(
      "Release the Inherited Provision",
      "Sorcery",
      "grave",
      6,
      "drain",
      7,
      "A collector's imagined violet spell unwinds a rigid ancestral seal and carries its light toward several plain household bowls, leaving every offered service cord unknotted.",
    ),
  ),
  H(
    "Keeper of the Open Threshold",
    "dawn",
    5,
    3,
    [
      [1, "shield", 2],
      [-2, "recall", 1],
      [-6, "heal", 8],
    ],
    "An invented human Lantern keeper moves a resting bench outward into the open court, shuttered lamp in hand, making room for another household.",
  ),
  H(
    "Patron of the Released Claim",
    "grave",
    5,
    4,
    [
      [1, "heal", 2],
      [-2, "drain", 3],
      [-7, "draw", 4],
    ],
    "An invented living vampiric Vesper patron lays an opened ancestral seal on a low table before standing human retainers, with no scene of feeding.",
  ),
];
