import {
  C,
  S,
  P,
  R,
  H,
  culture,
  rare,
  type LivingEntry,
} from "./living-expansion-tools";

/** Collector numbers 25–80: grounded cairnfolk, burrowfolk and unlike traveling households. */
export const unclaimedWaysExpansion: LivingEntry[] = [
  ...culture("Stone", [
    C(
      "Low-cairn Ropekeeper",
      "grove",
      1,
      1,
      2,
      "A short-beaked cairnfolk ropekeeper stands on two feet beside a low trail cairn, dexterous hands holding a tall pole and forearm fans folded tight.",
      { keywords: ["reach"] },
    ),
    C(
      "Switchback Footing Tender",
      "tide",
      2,
      2,
      3,
      "A grounded cairnfolk worker kneels at a mountain switchback and tests a repaired stone step with one hand; both folded forearm fans remain at their sides.",
      { keywords: ["rootfast"] },
    ),
    C(
      "Pack-rest Provisioner",
      "grove",
      3,
      3,
      3,
      "A short-beaked cairnfolk provisioner unloads seed sacks from a low trail cart, standing on ordinary walking legs with no outstretched wings.",
      { trigger: "gather" },
    ),
    C(
      "High-rail Path Guard",
      "tide",
      4,
      3,
      5,
      "A cairnfolk guard stands securely behind a mountain path rail, dexterous hands raising a long hook while their paired forearm fans stay folded.",
      { keywords: ["reach"] },
    ),
    S(
      "Share the Climbing Load",
      "Instant",
      "grove",
      1,
      "renew",
      1,
      "Two grounded cairnfolk walkers pass a heavy trail pack between dexterous hands at a stone rest landing, folded forearm fans visible.",
    ),
    S(
      "Brace the Missing Step",
      "Sorcery",
      "grove",
      3,
      "pump",
      4,
      "An imagined green spell settles around a cairnfolk worker's boots and hand-held brace as they restore one dangerous gap in a mountain stair.",
    ),
    P(
      "Cairn-side Pulley Frame",
      "Artifact",
      "tide",
      2,
      "mana-rock",
      "A small timber pulley frame raises a supply basket beside a stone trail marker, its weighted rope secured to the ground.",
    ),
    C(
      "Terrace Seed Courier",
      "grove",
      2,
      2,
      2,
      "A cairnfolk courier with a short beak walks between terrace beds, two dexterous hands steadying seed pouches above tightly folded forearm fans.",
      { trigger: "gather" },
    ),
    C(
      "Route-dispute Recorder",
      "tide",
      3,
      2,
      4,
      "A grounded cairnfolk recorder lays two different trail sketches on a low stone table with both dexterous hands; their forearm fans remain folded.",
      { effect: "draw", amount: 1 },
    ),
    C(
      "Long-rail Crossing Warden",
      "grove",
      4,
      4,
      4,
      "A short-beaked cairnfolk warden plants a long pole beside a repaired bridge rail, firmly on two feet with folded fans along their arms.",
      { keywords: ["reach", "vigilance"] },
    ),
    S(
      "Turn Back at the Loose Stones",
      "Instant",
      "tide",
      2,
      "bounce",
      1,
      "A collector's pale wind guides an approaching traveler back from a crumbling switchback toward a broad safe landing; no cairnfolk is flying.",
    ),
    S(
      "Raise the Shared Handrail",
      "Sorcery",
      "grove",
      3,
      "rally",
      1,
      "Grounded cairnfolk workers with folded forearm fans lift a practical timber handrail together along the outer edge of a mountain path.",
    ),
    P(
      "The Maintained Passage",
      "Enchantment",
      "tide",
      3,
      "recordwork",
      "Quiet blue light follows repaired rope joints and grounded trail tools beside a series of modest cairns; the route has no owner gate.",
    ),
    C(
      "Storm-step Concord Warden",
      "grove",
      6,
      6,
      6,
      "An ordinary-sized cairnfolk warden braces on two boots amid a storm, both dexterous hands gripping a long rescue pole and forearm fans folded against the coat.",
      { keywords: ["trample", "reach"] },
    ),
    S(
      "Trust the Repaired Footing",
      "Instant",
      "grove",
      3,
      "pump",
      4,
      "An imagined green glow steadies one cairnfolk trail keeper on newly set stones above a steep drop, with folded arm fans and both feet grounded.",
    ),
    P(
      "The Joined Rail Standard",
      "Artifact",
      "grove",
      4,
      "anthem",
      "A tall trail standard incorporates repaired handrail pieces and tightly bound rope, overlooking a safe mountain rest platform.",
    ),
  ]),
  ...culture("Verdancy", [
    C(
      "Low-door Air Tender",
      "tide",
      1,
      1,
      3,
      "A compact furred Underhush burrowfolk worker with rounded ears checks a low vent using broad-fingered hands; warm wall lamps reveal no deepfolk features.",
      { keywords: ["rootfast"] },
    ),
    C(
      "Shared-room Hearth Host",
      "grove",
      2,
      2,
      3,
      "A rounded-eared, furred burrowfolk host sets two different-height stools beside a low hearth, broad hands carrying a plain tray.",
      { trigger: "welcome" },
    ),
    C(
      "Quiet-passage Listener",
      "tide",
      3,
      2,
      4,
      "A compact Underhush burrowfolk listener holds a broad-fingered hand beside a tunnel sounding bowl, rounded ears turned toward approaching traffic.",
      { effect: "bind", amount: 1 },
    ),
    C(
      "Root-cellar Nourisher",
      "grove",
      4,
      3,
      5,
      "A furred burrowfolk caretaker with rounded ears carries a basket of living roots into a ventilated common cellar, broad hands clear in warm light.",
      { trigger: "lifegain" },
    ),
    S(
      "Wait for the Air Change",
      "Instant",
      "tide",
      2,
      "bind",
      1,
      "A collector's blue hush holds a traveler briefly beside an open tunnel vent while hanging air ribbons settle in a safe direction.",
    ),
    S(
      "Read the Room Soundings",
      "Sorcery",
      "tide",
      3,
      "draw",
      2,
      "Three differently shaped sounding bowls and soft hanging cords reveal the air and resonance of an inhabited burrowfolk exchange room.",
    ),
    P(
      "The Adjustable Guest Table",
      "Artifact",
      "grove",
      3,
      "welcome",
      "A practical low wooden table has removable risers and stools of different heights, ready for unlike visitors in a ventilated exchange room.",
    ),
    C(
      "Vent-shaft Hook Tender",
      "tide",
      2,
      1,
      4,
      "A short, furred burrowfolk tender stands beneath a narrow vent shaft, broad-fingered hands guiding a long cleaning hook above rounded ears.",
      { keywords: ["reach"] },
    ),
    C(
      "Doorway Clearance Keeper",
      "grove",
      3,
      3,
      3,
      "A compact Underhush keeper with rounded ears braces a low door open and points larger visitors toward an equally welcoming tall passage.",
      { keywords: ["rootfast", "vigilance"] },
    ),
    C(
      "Side-passage Guide",
      "tide",
      4,
      3,
      4,
      "A rounded-eared burrowfolk guide uses one broad hand to indicate a safe return passage while a low ceiling ahead remains under repair.",
      { effect: "bounce", amount: 1 },
    ),
    S(
      "Lend a Broader Grip",
      "Instant",
      "grove",
      2,
      "pump",
      2,
      "A collector's warm green spell strengthens the broad-fingered hands of one furred burrowfolk worker lifting a fallen door beam.",
    ),
    S(
      "Prepare the Quiet Recovery Room",
      "Sorcery",
      "grove",
      4,
      "heal",
      8,
      "Fresh root broth, clean woven bedding and open air vents fill a small burrowfolk resting room with a gentle green-gold glow.",
    ),
    P(
      "Room for Unlike Breathing",
      "Enchantment",
      "grove",
      3,
      "sanctuary",
      "Soft currents of green light follow open vents between rooms of different heights, with warm lamps and no sealed underground prison.",
    ),
    C(
      "Underhush Common-room Warden",
      "grove",
      5,
      4,
      6,
      "An ordinary-sized rounded-eared burrowfolk warden plants both feet beside a heavy open doorway, broad hands steady on a brace and a broth bowl.",
      { keywords: ["rootfast"], trigger: "lifegain" },
    ),
    S(
      "Refuse the Sealed Passage",
      "Instant",
      "tide",
      2,
      "counter",
      1,
      "An imagined blue vibration from a sounding bowl breaks a descending magical barrier before it seals an inhabited low doorway.",
    ),
    P(
      "The Ventilation Record Cabinet",
      "Artifact",
      "tide",
      4,
      "archive",
      "A low cabinet holds sounding bowls, removable air screens and separate room records, its worn broad handles sized for burrowfolk hands.",
    ),
  ]),
  ...culture("Spirit", [
    C(
      "Foxfolk First-path Runner",
      "grove",
      1,
      2,
      1,
      "An upright foxfolk courier in practical travel clothes runs along a woodland path, dexterous hands securing a small household message pouch.",
      { keywords: ["haste"] },
    ),
    C(
      "Deerfolk Crossing Witness",
      "tide",
      2,
      2,
      2,
      "An upright deerfolk traveler with modest antlers stands alert beside a narrow crossing, one dexterous hand marking a safe passage for another household.",
      { keywords: ["vigilance"] },
    ),
    C(
      "Boarfolk Waypost Keeper",
      "grove",
      3,
      3,
      4,
      "A clothed upright boarfolk keeper braces a practical wooden waypost with both dexterous hands while unlike travelers pass behind.",
      { keywords: ["rootfast"] },
    ),
    C(
      "Boarfolk Cartpath Breaker",
      "grove",
      4,
      4,
      4,
      "An upright boarfolk worker in a leather apron pushes a blocked handcart over a root ridge, two dexterous hands on the handles.",
      { keywords: ["trample"] },
    ),
    S(
      "Change the Leading Household",
      "Instant",
      "tide",
      2,
      "renew",
      1,
      "An upright deerfolk guide hands a trail marker to a rested foxfolk traveler, both clothed political people with separate household packs.",
    ),
    S(
      "Share the Roadside Meal",
      "Sorcery",
      "grove",
      2,
      "heal",
      5,
      "A low camp table holds distinct foxfolk, deerfolk and boarfolk traveling bowls around a simple vegetable stew, with no single clan banner.",
    ),
    P(
      "Many-height Trail Rack",
      "Artifact",
      "grove",
      2,
      "mana-rock",
      "A roadside timber rack carries hooks and pack rests at several heights, with separate household cords and a sturdy repair peg.",
    ),
    C(
      "Foxfolk Route-questioner",
      "tide",
      2,
      2,
      3,
      "An upright foxfolk delegate spreads a worn route cloth across a fallen log, dexterous hands pointing toward an overlooked household path.",
      { effect: "draw", amount: 1 },
    ),
    C(
      "Deerfolk Camp Host",
      "grove",
      3,
      3,
      3,
      "A clothed upright deerfolk host raises the edge of a woodland shelter to admit a short visitor, leaving space around their modest antlers.",
      { trigger: "welcome" },
    ),
    C(
      "Boarfolk Forage Steward",
      "grove",
      4,
      4,
      5,
      "An upright boarfolk steward uses dexterous hands to divide gathered roots among several separately marked traveling baskets.",
      { trigger: "gather" },
    ),
    S(
      "Answer Across the Camp",
      "Instant",
      "grove",
      3,
      "rally",
      1,
      "Separate foxfolk, deerfolk and boarfolk households raise practical travel tools in response to one urgent call across a woodland camp.",
    ),
    S(
      "Clear the Meeting Path",
      "Sorcery",
      "grove",
      4,
      "rally",
      2,
      "Unlike upright traveling peoples move fallen branches aside together, opening a route wide enough for different bodies without adopting one banner.",
    ),
    P(
      "No Household Left Outside",
      "Enchantment",
      "grove",
      3,
      "welcome",
      "Gentle green light links several differently sized woodland shelters, each with its own cords, utensils and open entrance.",
    ),
    C(
      "Boarfolk Long-road Warden",
      "grove",
      6,
      6,
      6,
      "An ordinary-sized upright boarfolk warden stands beside a broad handcart, a practical staff in dexterous hands and several separate household packs behind.",
      { keywords: ["trample", "vigilance"] },
    ),
    S(
      "Hear the Routes Not Taken",
      "Instant",
      "tide",
      4,
      "draw",
      3,
      "Three separate route cloths unfold in a sudden blue camp light, showing distinct paths through woodland and low hills without readable lettering.",
    ),
    P(
      "The Returning Path Beacon",
      "Artifact",
      "grove",
      4,
      "watchfire",
      "A shielded woodland beacon burns above a many-height pack rack, its steady amber light following several outgoing paths.",
    ),
  ]),
  R(
    "Root-sheltered Rest Glade",
    "grove",
    ["grove"],
    "common",
    "An empty woodland rest glade has a low root shelter, clear ground and small pools of sun between mossy trunks.",
  ),
  R(
    "Mossbank Passing Place",
    "grove",
    ["grove", "tide"],
    "uncommon",
    "A broad mossy passing place borders a slow mountain stream, with a low rail and space to wait for an oncoming cart.",
  ),
  R(
    "Sunlit Terrace Rest",
    "grove",
    ["grove", "dawn"],
    "rare",
    "A repaired terrace landing opens onto small food beds and a sheltered stone bench beneath warm dawn light.",
  ),
  R(
    "Lamplit Burrow Landing",
    "tide",
    ["tide", "grave"],
    "rare",
    "A quiet blue evening stream passes an inhabited burrow landing, its open vents and low lamps set beside a modest remembrance niche.",
  ),
  rare(
    P(
      "The Many-height Common Table",
      "Artifact",
      "grove",
      4,
      "anthem",
      "A collector's imagined adjustable camp table joins separate cairnfolk trail tools, burrowfolk bowls and Manytrack packs without combining their household signs.",
    ),
  ),
  rare(
    S(
      "Open Every Waiting Route",
      "Sorcery",
      "grove",
      5,
      "rally",
      3,
      "An invented comparison shows grounded mountain walkers, rounded-eared burrowfolk and upright woodland travelers moving along three distinct repaired routes.",
    ),
  ),
  H(
    "Warden of the Reachable Cairn",
    "grove",
    4,
    4,
    [
      [1, "pump", 1],
      [-2, "renew", 1],
      [-6, "rally", 2],
    ],
    "An invented short-beaked cairnfolk warden stands on two feet beside a low accessible cairn, both dexterous hands on a trail pole and forearm fans folded.",
  ),
  H(
    "Keeper of the Second Door",
    "tide",
    5,
    5,
    [
      [1, "shield", 2],
      [-3, "bounce", 1],
      [-7, "draw", 4],
    ],
    "An invented compact furred Underhush keeper with rounded ears opens a taller second doorway using broad-fingered hands, leaving the low entrance open too.",
  ),
];
