import {
  C,
  S,
  P,
  R,
  H,
  culture,
  rare,
  type LivingEntry,
} from "./living-expansion-tools";

/** Collector numbers 25–80. Existing numbers 1–24 are retained verbatim. */
export const sharedMeasureExpansion: LivingEntry[] = [
  // Cistern Assembly · 25–40
  ...culture("Oath", [
    C(
      "Newcomer Wallmender",
      "dawn",
      1,
      1,
      3,
      "A human newcomer presses lime into a cistern seam; the inherited keys remain on the far side of the hearing mat.",
      { keywords: ["rootfast"] },
    ),
    C(
      "Shade-gallery Watch",
      "dawn",
      2,
      2,
      3,
      "Under a turquoise awning, a human watchkeeper leaves the drawing path open while a hearing runs late.",
      { keywords: ["vigilance"] },
    ),
    C(
      "Notched-vessel Inspector",
      "tide",
      3,
      2,
      4,
      "A human inspector lowers three differently shaped jars beside one public measure, refusing a private calibration.",
      { trigger: "recordwork" },
    ),
    C(
      "Claim-bearing Gardener",
      "dawn",
      4,
      3,
      5,
      "A human gardener brings a living pomegranate branch and a worn rust cord to the shade court.",
      { trigger: "lifegain" },
    ),
    S(
      "Relieve the Drawing Watch",
      "Instant",
      "dawn",
      1,
      "renew",
      1,
      "A human relief worker takes the jar pole while the night keeper opens cramped hands beneath the last lantern.",
    ),
    S(
      "Read the Overflow Marks",
      "Sorcery",
      "tide",
      3,
      "draw",
      2,
      "Lamps held low reveal successive waterlines on a limewashed wall; no one has scrubbed the inconvenient marks away.",
    ),
    P(
      "Repairer's Level",
      "Artifact",
      "dawn",
      2,
      "mana-rock",
      "A wooden level, a plumb cord and a shallow water channel rest beside a newly mended cistern joint.",
    ),
    C(
      "Open-court Copyist",
      "tide",
      2,
      2,
      2,
      "A human copyist sets identical clay-backed copies at opposite edges of the public hearing mat.",
      { effect: "draw", amount: 1 },
    ),
    C(
      "Caravan Claim Witness",
      "dawn",
      3,
      3,
      3,
      "A human traveler unfolds a patched turquoise shelter for a household whose jars are still empty.",
      { trigger: "welcome" },
    ),
    C(
      "Keeper of the Late Queue",
      "dawn",
      4,
      4,
      4,
      "A human keeper carries the last filled jars into the deep blue hour, with the queue still under her care.",
      { keywords: ["vigilance", "lifelink"] },
    ),
    S(
      "Stay the Private Drawing",
      "Instant",
      "tide",
      2,
      "bind",
      1,
      "In a collector's imagined spell, pale water bands arrest a departing jar cart beside the public gate.",
    ),
    S(
      "Count Every Repairing Hand",
      "Sorcery",
      "dawn",
      3,
      "rally",
      1,
      "Human wallmenders lift different tools over the completed joint; an unfinished membership hearing waits behind them.",
    ),
    P(
      "The Public Calibration",
      "Enchantment",
      "tide",
      3,
      "recordwork",
      "Gentle rings of light connect the same three notches across unlike vessels in a crowded shade gallery.",
    ),
    C(
      "Cistern Rainwarden",
      "dawn",
      5,
      5,
      6,
      "A human warden braces the spill gate against a sudden desert storm, shielding both old household jars and newcomers' tools.",
      { keywords: ["rootfast", "vigilance"], trigger: "welcome" },
    ),
    S(
      "Honor the Uncounted Labor",
      "Instant",
      "dawn",
      4,
      "rally",
      2,
      "Warm light passes from a night repair crew's scarred hands to the waiting households beneath the turquoise canopy.",
    ),
    P(
      "Canopy of Equal Shade",
      "Artifact",
      "dawn",
      4,
      "anthem",
      "A broad joined canopy stands on repaired wooden uprights; its mismatched cloth panels cast one continuous shade.",
    ),
  ]),
  // Red Sluice Directorate · 41–56
  ...culture("Tide", [
    C(
      "Mudstep Messenger",
      "tide",
      1,
      1,
      2,
      "A human canal messenger carries a clean drinking flask along a narrow red-stained bank toward an exhausted work crew.",
      { effect: "heal", amount: 1 },
    ),
    C(
      "Shift Relief Runner",
      "dawn",
      2,
      2,
      2,
      "A human runner crosses a lowered timber gate with a replacement shift's knot-board strapped securely to her back.",
      { keywords: ["haste"] },
    ),
    C(
      "Long-pole Gate Tender",
      "tide",
      3,
      3,
      3,
      "A human gate tender hooks a drifting hazard from above the canal with a long iron-shod pole.",
      { keywords: ["reach"] },
    ),
    C(
      "Outbank Family Warden",
      "dawn",
      4,
      3,
      4,
      "A human warden holds a broad flood screen while marginal households carry bundles away from the rising channel.",
      { effect: "shield", amount: 3 },
    ),
    S(
      "Return Along the Towpath",
      "Instant",
      "tide",
      2,
      "bounce",
      1,
      "An imagined silver current turns an armed traveler gently back along the towpath, clear of the opening gate.",
    ),
    S(
      "A Crew for the Outlying Gates",
      "Sorcery",
      "dawn",
      3,
      "pump",
      3,
      "Several human crews brace one distant gate with fresh timbers while the central schedule hangs unanswered behind them.",
    ),
    P(
      "Portable Gate Winch",
      "Artifact",
      "tide",
      2,
      "mana-rock",
      "A compact timber-and-iron winch sits on a canal work sled, its wet rope reeved through a single sturdy pulley.",
    ),
    C(
      "Root-bank Surveyor",
      "tide",
      2,
      1,
      4,
      "A human surveyor kneels among reed roots and marks the household flood line below the board's raised platform.",
      { keywords: ["rootfast"] },
    ),
    C(
      "Relief-board Delegate",
      "dawn",
      3,
      3,
      3,
      "A human delegate lays down the emergency knot-board and calls the next rested gate crew forward.",
      { effect: "renew", amount: 1 },
    ),
    C(
      "Chain-house Recorder",
      "tide",
      4,
      3,
      5,
      "A human recorder checks a replacement chain beside its broken predecessor in a red-brick maintenance house.",
      { trigger: "recordwork" },
    ),
    S(
      "Close the Breach Screens",
      "Instant",
      "dawn",
      2,
      "shield",
      6,
      "Three overlapping timber screens take the flood's force while lanterns remain visible in the houses behind them.",
    ),
    S(
      "Publish the Pumping Burden",
      "Sorcery",
      "tide",
      4,
      "draw",
      3,
      "A human crew unrolls a large physical channel plan beside muddy household tokens and three separate work ledgers.",
    ),
    P(
      "Between the Scheduled Bells",
      "Enchantment",
      "dawn",
      3,
      "sanctuary",
      "Resting human workers share a warm shelter between two silent canal bells, with tools hung beyond the dry bench.",
    ),
    C(
      "Breakwater Crew Captain",
      "dawn",
      5,
      4,
      6,
      "An unnamed human captain raises a plain work pennant as separate crews settle the last flood barrier into place.",
      { effect: "rally", amount: 1 },
    ),
    S(
      "Read the Emergency Addendum",
      "Instant",
      "tide",
      4,
      "draw",
      3,
      "A rain-soaked human courier opens a sealed supplementary record beneath a hand-held lantern before the gate lever can fall.",
    ),
    P(
      "Ledger of Returned Seals",
      "Artifact",
      "tide",
      4,
      "archive",
      "Retired work seals lie beside a stitched ledger on a canal board's plain desk; none remains hanging from an officer's belt.",
    ),
  ]),
  // Brine Choir · 57–72
  ...culture("Rune", [
    C(
      "Tidepool Caretaker",
      "tide",
      1,
      1,
      2,
      "A two-legged blue-grey brinefolk caretaker, small neck fins visible, cups clean pool water for a tired shore visitor.",
      { keywords: ["lifelink"] },
    ),
    C(
      "Shared-quay Greeter",
      "dawn",
      2,
      2,
      3,
      "A brinefolk greeter with dexterous hands and ordinary walking legs makes room on a shell-marked quay for a human household.",
      { trigger: "welcome" },
    ),
    C(
      "Pool-boundary Listener",
      "tide",
      3,
      2,
      3,
      "A standing brinefolk listener raises a cord of shell markers between two landing parties, leaving the water itself unclaimed.",
      { effect: "bind", amount: 1 },
    ),
    C(
      "High-net Landing Guard",
      "dawn",
      4,
      3,
      5,
      "A brinefolk guard stands on two feet beneath a raised rope net, her small neck fins sheltered by a salt-worn collar.",
      { keywords: ["reach"] },
    ),
    S(
      "Lend the Shoreward Strength",
      "Instant",
      "dawn",
      2,
      "pump",
      2,
      "A human and a brinefolk worker lift opposite ends of a stranded skiff as a collector's warm spell steadies their arms.",
    ),
    S(
      "Refresh the Waiting Pools",
      "Sorcery",
      "dawn",
      2,
      "heal",
      5,
      "Clear water spills through opened stone channels into quiet shore pools beneath folded reed shades.",
    ),
    P(
      "Shell-cord Reception Rack",
      "Artifact",
      "tide",
      3,
      "welcome",
      "A wooden quay rack carries distinct shell cords, dry towels and drinking bowls prepared for unlike arriving households.",
    ),
    C(
      "Harbor Vessel Witness",
      "tide",
      2,
      2,
      3,
      "A brinefolk witness holds a repaired clay vessel at eye level, comparing its seam with the maintenance cord on the quay.",
      { trigger: "recordwork" },
    ),
    C(
      "Low-tide Crossing Guide",
      "dawn",
      3,
      2,
      5,
      "A brinefolk guide walks upright across exposed shore stones and plants a hand-held marker where human children can reach it.",
      { keywords: ["vigilance"] },
    ),
    C(
      "Outer-pool Pathwarden",
      "tide",
      4,
      3,
      4,
      "A blue-grey brinefolk pathwarden gestures toward the safe return channel while a disputed landing remains closed for repair.",
      { effect: "bounce", amount: 1 },
    ),
    S(
      "Reject the Exclusive Landing",
      "Instant",
      "tide",
      3,
      "counter",
      1,
      "An imagined arc from a raised shell cord breaks a descending magical seal above a shared shore landing.",
    ),
    S(
      "Gather at the Common Steps",
      "Sorcery",
      "dawn",
      4,
      "rally",
      2,
      "Distinct human and two-legged brinefolk households bring separate tools to wide repaired quay steps without sharing a single banner.",
    ),
    P(
      "A Place Beside the Pool",
      "Enchantment",
      "dawn",
      3,
      "welcome",
      "A gentle magical glow links unlike resting places around one shore pool, leaving each household's belongings distinct.",
    ),
    C(
      "Deep-shore Custodian",
      "tide",
      6,
      5,
      6,
      "A mature brinefolk custodian stands firmly on two legs in a storm-washed shore court, both hands steady on a broad rescue pole.",
      { keywords: ["rootfast", "lifelink"] },
    ),
    S(
      "Carry the Last Vessel Ashore",
      "Instant",
      "dawn",
      3,
      "heal",
      8,
      "Human and brinefolk hands receive a glowing rescue jar from a rough sea; the quay lanterns remain sheltered behind them.",
    ),
    P(
      "Concordance of Shore Repairs",
      "Artifact",
      "tide",
      4,
      "recordwork",
      "Separate shell cords, jar fragments and human tally boards surround one carefully repaired shore-basin model.",
    ),
  ]),
  R(
    "Morning Drawing Garden",
    "dawn",
    ["dawn"],
    "common",
    "An imagined limewashed kitchen garden drinks from a narrow cistern channel under soft morning light; no large foreground figure.",
  ),
  R(
    "Paired Sluice Steps",
    "dawn",
    ["dawn", "tide"],
    "uncommon",
    "Two practical stairs meet above a slow canal gate, with dry landings for separate work crews; access must wait for the gate cycle.",
  ),
  R(
    "Caravan Orchard Turn",
    "dawn",
    ["dawn", "grove"],
    "rare",
    "A shaded orchard turnout joins the drawing garden to a caravan path; water vessels and fruit trees share a carefully tended verge.",
  ),
  R(
    "Tide-mark Memorial Court",
    "tide",
    ["tide", "grave"],
    "rare",
    "Quiet tidal channels surround a shore memorial court of glazed jars, shell cords and low stone benches in blue evening light.",
  ),
  rare(
    P(
      "The Many-handed Workbench",
      "Artifact",
      "dawn",
      4,
      "welcome",
      "A collector's imagined common bench holds distinct canal, cistern and shore tools, with separate places prepared for each arriving repairer.",
    ),
  ),
  rare(
    S(
      "Reopen the Common Works",
      "Sorcery",
      "dawn",
      5,
      "rally",
      3,
      "In an invented comparison of the three cultures, repaired channels open together beneath distinct crews and different household signs.",
    ),
  ),
  H(
    "Steward of the Second Hearing",
    "dawn",
    4,
    4,
    [
      [1, "heal", 2],
      [-2, "shield", 5],
      [-7, "rally", 3],
    ],
    "An invented human Cistern steward brings a second hearing mat into the shade, making space for the workers whose first claim was missed.",
  ),
  H(
    "Keeper of the Relinquished Seal",
    "tide",
    5,
    4,
    [
      [1, "renew", 1],
      [-2, "bind", 1],
      [-6, "draw", 4],
    ],
    "An invented human Directorate keeper sets the emergency seal on an open public desk, with the ordinary gate crews visible beyond him.",
  ),
];
