import type {
  Card,
  CardType,
  Effect,
  HeroAbility,
  ManaColor,
  Rarity,
} from "./catalog";
import { livingSets, livingSetIdentities } from "./living-cultures";
import { tableWords } from "./wording";

type Entry = Pick<
  Card,
  "name" | "type" | "color" | "cost" | "rarity" | "flavor"
> &
  Partial<Card>;
const companion = (
  name: string,
  color: ManaColor,
  cost: number,
  attack: number,
  health: number,
  rarity: Rarity,
  flavor: string,
  traits: Partial<Card> = {},
): Entry => ({
  name,
  color,
  cost,
  attack,
  health,
  rarity,
  flavor,
  type: "Creature",
  ...traits,
});
const spell = (
  name: string,
  type: "Instant" | "Sorcery",
  color: ManaColor,
  cost: number,
  effect: Effect,
  amount: number,
  rarity: Rarity,
  flavor: string,
): Entry => ({ name, type, color, cost, effect, amount, rarity, flavor });
const permanent = (
  name: string,
  type: "Artifact" | "Enchantment",
  color: ManaColor,
  cost: number,
  permanentEffect: Card["permanentEffect"],
  rarity: Rarity,
  flavor: string,
): Entry => ({ name, type, color, cost, permanentEffect, rarity, flavor });

const effectText = (effect: Effect, n: number): string =>
  ({
    none: "",
    damage: `Deal ${n} damage to a hearth, companion or Hero.`,
    heal: `Gain ${n} life.`,
    draw: `Draw ${n} ${n === 1 ? "card" : "cards"}.`,
    destroy: "Destroy target companion.",
    bounce: "Return target companion to its owner's hand.",
    counter: "Counter target spell or ability.",
    pump: `Target companion gets +${n}/+${n} until end of turn.`,
    recall:
      "Return your most recently fallen companion from your graveyard to your hand.",
    shield: `Prevent the next ${n} damage to your hearth.`,
    bind: "Exhaust target companion; it skips its next ready step.",
    renew:
      "Ready target companion and remove its binding. Arrival fatigue still applies.",
    drain: `Deal ${n} damage to the opposing hearth. Gain life equal to damage dealt after shields.`,
    rally: `Your companions get +${n}/+${n} until end of turn.`,
  })[effect];
const hero = (
  name: string,
  color: ManaColor,
  cost: number,
  loyalty: number,
  powers: [number, Effect, number][],
  flavor: string,
): Entry => ({
  name,
  type: "Hero",
  color,
  cost,
  loyalty,
  rarity: "mythic",
  flavor,
  abilities: powers.map(([loyalty, effect, amount]): HeroAbility => ({
    loyalty,
    effect,
    amount,
    text: `${loyalty > 0 ? "+" : ""}${loyalty}: ${effectText(effect, amount)}`,
  })),
});

/** Six authored cards per culture, followed by five basics and one dual.
 * Collector order is stable. A folio compares societies without making them allies. */
const entries: Record<string, Entry[]> = {
  "shared-measure": [
    companion(
      "Cistern Maintenance Hand",
      "dawn",
      1,
      1,
      2,
      "common",
      "The oldest drawing claim could not mend a cracked wall.",
      { keywords: ["vigilance"] },
    ),
    companion(
      "Public Measure Reader",
      "tide",
      3,
      2,
      4,
      "uncommon",
      "She set the measure where both the old households and the newcomers could see it.",
      { trigger: "recordwork" },
    ),
    spell(
      "Shade for the Waiting",
      "Instant",
      "dawn",
      1,
      "shield",
      4,
      "common",
      "A length of turquoise cloth made a little room for patience.",
    ),
    spell(
      "Hear the Repair Claim",
      "Sorcery",
      "tide",
      3,
      "draw",
      2,
      "uncommon",
      "The repairer's rust cord lay beside the inherited key. Both would be heard.",
    ),
    permanent(
      "Three-notch Measure",
      "Artifact",
      "tide",
      2,
      "mana-rock",
      "uncommon",
      "Three plain cuts made a private vessel answer a public question.",
    ),
    hero(
      "Speaker of the Open Cistern",
      "dawn",
      4,
      3,
      [
        [1, "shield", 2],
        [-2, "renew", 1],
        [-6, "rally", 3],
      ],
      "An imagined speaker leaves the shaded seat to stand among the waiting households.",
    ),
    companion(
      "Outlying Gatekeeper",
      "tide",
      2,
      2,
      3,
      "common",
      "The last gate on the schedule was the first gate her neighbors needed.",
    ),
    companion(
      "Chain-brace Forewoman",
      "dawn",
      3,
      3,
      4,
      "uncommon",
      "Her crew could steady the wheel. They could not steady the board's promises.",
      { keywords: ["reach"] },
    ),
    spell(
      "Suspend the Pump Order",
      "Instant",
      "tide",
      2,
      "bind",
      1,
      "common",
      "The chain stopped short; beyond the spillway, an uncounted household waited.",
    ),
    spell(
      "Release the Night Shift",
      "Sorcery",
      "dawn",
      1,
      "renew",
      1,
      "uncommon",
      "A relief crew arrived beneath the rain shields with dry cord and a hot meal.",
    ),
    permanent(
      "The Unending Emergency",
      "Enchantment",
      "tide",
      3,
      "recordwork",
      "rare",
      "Each repaired fitting entered the register; the emergency's final page stayed blank.",
    ),
    hero(
      "Advocate of the Last Gate",
      "tide",
      5,
      4,
      [
        [1, "shield", 1],
        [-2, "bind", 1],
        [-6, "draw", 3],
      ],
      "An invented household advocate carries a brick-red shield into the pump hearing.",
    ),
    companion(
      "Pool-court Listener",
      "dawn",
      2,
      2,
      3,
      "common",
      "The brinefolk listener folded her neck fins and made room for the shore household.",
    ),
    companion(
      "Shared Landing Steward",
      "tide",
      3,
      2,
      4,
      "uncommon",
      "The human steward greeted each boat before asking whose coin had built the quay.",
      { trigger: "welcome" },
    ),
    spell(
      "Return to the Common Pool",
      "Instant",
      "tide",
      2,
      "bounce",
      1,
      "common",
      "A pale current turned the escort toward the pool court, where another hearing waited.",
    ),
    spell(
      "A Hearing for Every Shore",
      "Sorcery",
      "dawn",
      4,
      "rally",
      2,
      "rare",
      "Separate voices carried across the water. Agreement was not the price of being heard.",
    ),
    permanent(
      "Shell-rimmed Hearing Bowl",
      "Artifact",
      "dawn",
      3,
      "sanctuary",
      "rare",
      "No one household kept the bowl; each left it clean for the next hearing.",
    ),
    hero(
      "Speaker Between the Pools",
      "tide",
      5,
      4,
      [
        [1, "heal", 1],
        [-2, "bounce", 1],
        [-6, "rally", 3],
      ],
      "An imagined brinefolk speaker stands on the low bridge, with human and brinefolk households on either bank.",
    ),
  ],
  "terms-of-shelter": [
    companion(
      "Civilian Roll Keeper",
      "dawn",
      1,
      2,
      2,
      "common",
      "Her roll case listed the wagon's dependents before its spearheads.",
    ),
    companion(
      "Contract-end Veteran",
      "grave",
      3,
      3,
      4,
      "uncommon",
      "He had buried companions under three banners. His children owed none of them.",
      { trigger: "mourning" },
    ),
    spell(
      "Hold Until the Last Wagon",
      "Instant",
      "dawn",
      1,
      "pump",
      2,
      "common",
      "Reused plate and a finite promise held the road until the families had passed.",
    ),
    spell(
      "Call the Veteran Home",
      "Sorcery",
      "grave",
      2,
      "recall",
      1,
      "uncommon",
      "In the collector's telling, a memorial lantern recalled a defender to the wagon court.",
    ),
    permanent(
      "A Service Freely Ended",
      "Enchantment",
      "dawn",
      3,
      "welcome",
      "uncommon",
      "At the canvas doorway, a returned roll case was met with a place at supper.",
    ),
    hero(
      "Auditor of the Wagon Court",
      "dawn",
      4,
      3,
      [
        [1, "shield", 2],
        [-2, "pump", 2],
        [-6, "rally", 3],
      ],
      "This imagined auditor lays the campaign purse before the households who filled it.",
    ),
    companion(
      "Open-court Attendant",
      "dawn",
      2,
      2,
      3,
      "common",
      "She opened the lamp shutter only after opening the room to fresh air.",
      { effect: "heal", amount: 1 },
    ),
    companion(
      "Linen-store Escort",
      "dawn",
      3,
      2,
      4,
      "uncommon",
      "Her shield guarded folded linen and clean bowls more often than any dignitary.",
      { keywords: ["vigilance"], trigger: "welcome" },
    ),
    spell(
      "Rest Before the Next Watch",
      "Instant",
      "dawn",
      2,
      "heal",
      4,
      "common",
      "A warm cup, a clean blanket and someone willing to take the next watch.",
    ),
    spell(
      "Open the Shuttered Court",
      "Sorcery",
      "dawn",
      3,
      "rally",
      1,
      "uncommon",
      "The attendants brought benches into daylight. Their welcome could be seen from the road.",
    ),
    permanent(
      "Ventilated Care Lantern",
      "Artifact",
      "dawn",
      3,
      "sanctuary",
      "rare",
      "The flame breathed through small shutters; the people around it could breathe too.",
    ),
    hero(
      "Keeper of the Unbarred Door",
      "dawn",
      5,
      4,
      [
        [1, "heal", 2],
        [-2, "renew", 1],
        [-6, "shield", 8],
      ],
      "An imagined hospice keeper stands beside the open court, holding a plain yellow lamp.",
    ),
    companion(
      "Redshutter Retainer",
      "grave",
      2,
      3,
      2,
      "common",
      "The living guard's wage bought bread. It did not buy the next generation's blood.",
    ),
    companion(
      "Revocable-provision Advocate",
      "grave",
      3,
      3,
      4,
      "uncommon",
      "She placed an empty silver vessel beside the tenancy roll and asked what refusal would cost.",
      { keywords: ["rootfast"] },
    ),
    spell(
      "Close the Provision Ledger",
      "Instant",
      "grave",
      2,
      "drain",
      2,
      "common",
      "In this invented spell, only a measured thread of dusk-light crossed between hearths.",
    ),
    spell(
      "Release the Inherited Claim",
      "Sorcery",
      "grave",
      4,
      "destroy",
      1,
      "rare",
      "A collector imagines the old claim breaking around a spectral guardian, leaving the tenant's door intact.",
    ),
    permanent(
      "Court of Recalled Terms",
      "Enchantment",
      "grave",
      4,
      "archive",
      "rare",
      "Younger patrons laid contradictory memories on the same velvet-covered table.",
    ),
    hero(
      "Patron of the Unpledged House",
      "grave",
      5,
      4,
      [
        [1, "shield", 1],
        [-2, "drain", 2],
        [-6, "recall", 1],
      ],
      "An invented vampiric patron sets aside the silver cup while a living household speaks; no biography is asserted.",
    ),
  ],
  "unclaimed-ways": [
    companion(
      "Lower-port Rigger",
      "tide",
      1,
      1,
      2,
      "common",
      "The human rigger tested each oxblood rope before the upper council began its ascent.",
    ),
    companion(
      "Cairnfolk Approach Watcher",
      "grove",
      3,
      2,
      5,
      "uncommon",
      "Folded forearm feathers left both hands free for the hooked staff and signal cord.",
      { keywords: ["reach"] },
    ),
    spell(
      "Brace the Loaded Lift",
      "Instant",
      "grove",
      1,
      "pump",
      2,
      "common",
      "Boots found pale scree; a copper bracket held while the load swung back to safety.",
    ),
    spell(
      "Read the Lift Accounts",
      "Sorcery",
      "tide",
      3,
      "draw",
      2,
      "uncommon",
      "The lower workers brought worn harnesses to a hearing about upper precedence.",
    ),
    permanent(
      "Common Passage Harness",
      "Artifact",
      "tide",
      2,
      "mana-rock",
      "uncommon",
      "A spare clasp cost less than a household stranded above the broken lift.",
    ),
    hero(
      "Speaker of the Lower Bracket",
      "tide",
      5,
      4,
      [
        [1, "shield", 2],
        [-2, "draw", 2],
        [-6, "rally", 3],
      ],
      "An imagined cairnfolk speaker stands on two booted legs, dexterous feathered arms resting on a lift rail.",
    ),
    companion(
      "Gallery Vent Tender",
      "grove",
      2,
      2,
      2,
      "common",
      "The burrowfolk tender measured a good trade by the air left for the rooms behind it.",
      { keywords: ["rootfast"] },
    ),
    companion(
      "Tally-bead Fitter",
      "tide",
      3,
      3,
      3,
      "uncommon",
      "Broad fingered hands balanced a pewter fitting against the beads of a disputed lease.",
      { trigger: "recordwork" },
    ),
    spell(
      "Quiet the Trading Hall",
      "Instant",
      "tide",
      2,
      "bind",
      1,
      "common",
      "For one blessed pause, the gallery's hanging bowls stopped trembling.",
    ),
    spell(
      "Reopen the Homeward Vent",
      "Sorcery",
      "grove",
      1,
      "renew",
      1,
      "uncommon",
      "Cool air reached the sleeping rooms before the market reopened.",
    ),
    permanent(
      "The Habitable Lease",
      "Enchantment",
      "grove",
      3,
      "welcome",
      "rare",
      "Every new arrival had to leave room for those already sleeping behind the keyhole arches.",
    ),
    hero(
      "Steward of the Quiet Gallery",
      "grove",
      4,
      3,
      [
        [1, "heal", 1],
        [-2, "renew", 1],
        [-6, "rally", 3],
      ],
      "An imagined burrowfolk steward holds a vent key in one broad hand and a household tally in the other.",
    ),
    companion(
      "Foxfolk Path Speaker",
      "grove",
      2,
      3,
      2,
      "common",
      "The foxlike citizen carried a walking staff and three households' requests, not their authority.",
    ),
    companion(
      "Deerfolk Threshold Guard",
      "grove",
      3,
      2,
      4,
      "uncommon",
      "He left the broad arch clear for a neighbor whose antlers took a different span.",
      { trigger: "gather" },
    ),
    spell(
      "Leave a Gap in the Fence",
      "Instant",
      "grove",
      2,
      "renew",
      1,
      "common",
      "A tired guard rose as the crossed cords were loosened for the seasonal passage.",
    ),
    spell(
      "Many Voices, One Crossing",
      "Sorcery",
      "grove",
      4,
      "rally",
      2,
      "rare",
      "Human, horned and furred speakers crossed together without surrendering their separate claims.",
    ),
    permanent(
      "Bells of the Varied Threshold",
      "Artifact",
      "grove",
      4,
      "anthem",
      "rare",
      "The bells hung at different heights. Nobody had to stoop to announce a visit.",
    ),
    hero(
      "Boarfolk Marshal of the Moot",
      "grove",
      5,
      4,
      [
        [1, "heal", 1],
        [-2, "pump", 2],
        [-6, "rally", 4],
      ],
      "This invented boarlike marshal carries a linen-wrapped staff and listens before moving the crossed route cords.",
    ),
  ],
  "unfinished-answer": [
    companion(
      "Public Meridian Observer",
      "tide",
      1,
      1,
      2,
      "common",
      "Her weighted hem stayed still long enough to mark where the plumb line disagreed.",
      { trigger: "spellcraft" },
    ),
    companion(
      "Madder-cloth Calibrator",
      "tide",
      2,
      1,
      3,
      "uncommon",
      "Two unequal stitches made an error visible that a perfect circle had concealed.",
      { trigger: "recordwork" },
    ),
    spell(
      "Question the Certain Chart",
      "Instant",
      "tide",
      2,
      "counter",
      1,
      "common",
      "The measured line met the confident arc. The arc broke first.",
    ),
    spell(
      "Publish the Unequal Stitches",
      "Sorcery",
      "tide",
      3,
      "draw",
      2,
      "uncommon",
      "A cloth carrying the disputed measure hung where any passerby could compare it.",
    ),
    permanent(
      "Public Observatory Disc",
      "Artifact",
      "tide",
      2,
      "mana-rock",
      "uncommon",
      "The calibrated disc belonged on the low observatory's public table.",
    ),
    hero(
      "Reader of the Unequal Line",
      "tide",
      5,
      4,
      [
        [1, "shield", 1],
        [-2, "draw", 2],
        [-6, "bind", 1],
      ],
      "An imagined observer folds a chart beside a plumb line, keeping room for a later correction.",
    ),
    companion(
      "Firebreak Garden Keeper",
      "ember",
      1,
      2,
      1,
      "common",
      "Her seed jar was ordinary clay; keeping it safe was the difficult part.",
    ),
    companion(
      "Ash-screen Kilnhand",
      "ember",
      3,
      3,
      3,
      "uncommon",
      "Behind an ash-white ceramic screen, the human kiln worker practiced a measured flame.",
      { trigger: "spellcraft" },
    ),
    spell(
      "Contain the Kiln Flare",
      "Instant",
      "ember",
      2,
      "damage",
      3,
      "common",
      "The collector's spell bent the flare away from the seed jars and toward a single threat.",
    ),
    spell(
      "Carry the Garden Home",
      "Sorcery",
      "ember",
      2,
      "recall",
      1,
      "uncommon",
      "A remembered gardener followed one surviving seed through an imagined ember-lit memorial.",
    ),
    permanent(
      "Renewal Without Burning",
      "Enchantment",
      "ember",
      4,
      "watchfire",
      "rare",
      "Residents kept a watch flame behind ceramic screens; the teaching caravan had already moved on.",
    ),
    hero(
      "Keeper of the Unburned Seed",
      "ember",
      5,
      4,
      [
        [1, "shield", 1],
        [-2, "damage", 3],
        [-6, "recall", 1],
      ],
      "An imagined human keeper shelters a seed jar behind a half-blackened wheel, refusing to explain the Ashfall.",
    ),
    companion(
      "Archive Supply Witness",
      "tide",
      2,
      1,
      3,
      "common",
      "Before the custodians opened the case, the supply witness counted the household grain.",
    ),
    companion(
      "Interrupted-line Custodian",
      "tide",
      3,
      2,
      3,
      "uncommon",
      "She left the missing line visible rather than completing it from hope.",
      { effect: "draw", amount: 1 },
    ),
    spell(
      "Withhold the Opening Order",
      "Instant",
      "tide",
      2,
      "bind",
      1,
      "common",
      "A cinnabar cord crossed the weathered lead case until its safeguards could be heard.",
    ),
    spell(
      "Record the Failed Trial",
      "Sorcery",
      "tide",
      4,
      "draw",
      3,
      "rare",
      "The failed apparatus stood beside three open accounts. None had been scrubbed clean.",
    ),
    permanent(
      "Grain Owed to the Margin",
      "Enchantment",
      "tide",
      4,
      "archive",
      "rare",
      "When the archive's shelves ran quiet, the supplying households asked for the next account.",
    ),
    hero(
      "Witness of the Unopened Case",
      "tide",
      5,
      4,
      [
        [1, "heal", 1],
        [-2, "bounce", 1],
        [-6, "draw", 3],
      ],
      "An imagined human custodian keeps both hands on a closed lead case; uncertainty remains part of the record.",
    ),
  ],
};

const resourceNames: Record<string, string[]> = {
  "shared-measure": [
    "Cistern Shade Court",
    "Paired Hearing Pools",
    "Canal Memorial Bank",
    "Chain-forge Hearth",
    "Draw-share Garden",
    "The Common Landing",
  ],
  "terms-of-shelter": [
    "Hospice Morning Court",
    "Linen Washing Reach",
    "Shuttered Vineyard",
    "Wagon Repair Fire",
    "Tenants' Kitchen Garden",
    "The Revocable Threshold",
  ],
  "unclaimed-ways": [
    "Lower-port Sun Terrace",
    "Gallery Cooling Pool",
    "Cairn of the Lost Riggers",
    "Pewter Fitter's Hearth",
    "The Varied-height Grove",
    "Three-household Crossing",
  ],
  "unfinished-answer": [
    "Schoolroom Dawn Yard",
    "Meridian Reflecting Pool",
    "Archive of Failed Trials",
    "Seed-keeper's Kiln",
    "The Unburned Plot",
    "The Public Trial Court",
  ],
};
const colors: ManaColor[] = ["dawn", "tide", "grave", "ember", "grove"];
const resourceTraditions = [
  "Radiance",
  "Tide",
  "Grave",
  "Flame",
  "Verdancy",
] as const;
const triggerText: Record<Card["trigger"], string> = {
  none: "",
  gather:
    "Gather: whenever a resource enters under your control, this gets a +1/+1 counter.",
  spellcraft:
    "Spellcraft: whenever you cast an instant or sorcery, this gets a +1/+1 counter.",
  lifegain: "Fellowship: whenever you gain life, this gets a +1/+1 counter.",
  mourning:
    "Mourning: whenever another friendly companion dies, the opposing hearth loses 1 life.",
  welcome: "Welcome: whenever another friendly companion enters, gain 1 life.",
  recordwork:
    "Recordwork: the first friendly artifact that enters each turn lets you draw a card.",
};
const permanentText: Record<Card["permanentEffect"], string> = {
  none: "",
  "mana-rock": "",
  anthem: "Your companions get +1/+1.",
  sanctuary: "At the start of your turn, gain 1 life.",
  watchfire: "At the start of your turn, deal 1 damage to the opposing hearth.",
  archive:
    "At the start of your turn, if you have 3 or fewer cards in hand, draw a card.",
  welcome: "Whenever a friendly companion enters, gain 1 life.",
  recordwork:
    "The first friendly artifact that enters each turn lets you draw a card.",
};
const keywords: Partial<Record<Card["keywords"][number], string>> = {
  rootfast: "Rootfast: cannot be returned to hand by spells.",
  daunt: "Daunt: companions with 1 or less power cannot block this.",
};
export const livingCards: Card[] = livingSets.flatMap((set) => {
  const resources: Entry[] = resourceNames[set.id].map((name, i) => ({
    name,
    type: (i < 5 ? "Basic Resource" : "Special Resource") as CardType,
    color: colors[i] ?? livingSetIdentities[set.id].colors[0],
    cost: 0,
    colored: 0,
    rarity: i < 5 ? "common" : "uncommon",
    tradition: resourceTraditions[i] ?? "Oath",
    produces: i < 5 ? [colors[i]] : [...livingSetIdentities[set.id].colors],
    entersTapped: i === 5,
    flavor:
      i < 5
        ? `${name}: an imagined place of daily provision, maintained by present households rather than promised by a perfect history.`
        : `${name}: a collector's imagined meeting place. Shared access takes time, and neither household can grant it alone.`,
  }));
  return [...entries[set.id], ...resources].map((entry, i) => {
    const card: Card = {
      id: `${set.id}.${i + 1}`,
      setId: set.id,
      number: i + 1,
      art: `card.${set.id}.${i + 1}`,
      tradition: set.traditions[Math.floor(i / 6) % 3],
      colored: entry.cost >= 4 ? 2 : entry.cost > 0 ? 1 : 0,
      attack: 0,
      health: 0,
      effect: "none",
      amount: 0,
      keywords: [],
      produces: [],
      entersTapped: false,
      loyalty: 0,
      abilities: [],
      trigger: "none",
      permanentEffect: "none",
      rules: "",
      ...entry,
    };
    card.rules = tableWords(
      card.type.includes("Resource")
        ? `${card.entersTapped ? "Enters exhausted. " : ""}Exhaust: add one ${card.produces.join(" or ")} mana.`
        : card.type === "Hero"
          ? card.abilities.map((a) => a.text).join(" ")
          : [
              card.keywords.map((k) => keywords[k] ?? k).join(". "),
              triggerText[card.trigger],
              card.permanentEffect === "mana-rock"
                ? `Exhaust: add one ${card.color} mana.`
                : permanentText[card.permanentEffect],
              card.effect !== "none"
                ? `${card.type === "Creature" ? "When this enters: " : ""}${effectText(card.effect, card.amount)}`
                : "",
            ]
              .filter(Boolean)
              .join(" ") || "A companion of the present households.",
    );
    return card;
  });
});

/** Exact ordinary-card recipes: no mythic is needed and the old recipe builder
 * remains unchanged. Forty basics plus fifteen four-copy choices make 100. */
export const livingRecipes = [
  {
    id: "common-works",
    name: "Keep the Common Works",
    colors: ["dawn", "tide"] as ManaColor[],
    sets: ["shared-measure", "witness-roads"],
    plan: "Bind an attacker, ready a defender and play artifacts with a Public Measure Reader. Multiple cheap attackers stretch the shields.",
    basics: ["shared-measure.19", "shared-measure.20"],
    choices: [
      "shared-measure.1",
      "shared-measure.2",
      "shared-measure.7",
      "shared-measure.8",
      "shared-measure.13",
      "shared-measure.14",
      "shared-measure.5",
      "shared-measure.9",
      "shared-measure.10",
      "shared-measure.15",
      "shared-measure.16",
      "witness-roads.1",
      "witness-roads.66",
      "witness-roads.67",
      "witness-roads.78",
    ],
  },
  {
    id: "freely-given",
    name: "A Service Freely Given",
    colors: ["dawn", "grave"] as ManaColor[],
    sets: ["terms-of-shelter", "reckoning"],
    plan: "Welcome a protecting line, trade a veteran and recall it to hand. Drain closes a stalled hearth; early evasive pressure punishes the setup.",
    basics: ["terms-of-shelter.19", "terms-of-shelter.21"],
    choices: [
      "terms-of-shelter.1",
      "terms-of-shelter.2",
      "terms-of-shelter.7",
      "terms-of-shelter.8",
      "terms-of-shelter.13",
      "terms-of-shelter.14",
      "terms-of-shelter.3",
      "terms-of-shelter.4",
      "terms-of-shelter.5",
      "terms-of-shelter.15",
      "terms-of-shelter.16",
      "terms-of-shelter.17",
      "reckoning.1",
      "reckoning.19",
      "reckoning.67",
    ],
  },
  {
    id: "every-threshold",
    name: "Room at Every Threshold",
    colors: ["grove", "tide"] as ManaColor[],
    sets: ["unclaimed-ways", "deepfen"],
    plan: "Gather resources behind Highguard and Rootfast companions, then rally. Remove the growing guard before committing attackers.",
    basics: ["unclaimed-ways.23", "unclaimed-ways.20"],
    choices: [
      "unclaimed-ways.1",
      "unclaimed-ways.2",
      "unclaimed-ways.7",
      "unclaimed-ways.8",
      "unclaimed-ways.13",
      "unclaimed-ways.14",
      "unclaimed-ways.3",
      "unclaimed-ways.5",
      "unclaimed-ways.9",
      "unclaimed-ways.15",
      "unclaimed-ways.16",
      "unclaimed-ways.11",
      "deepfen.1",
      "deepfen.19",
      "deepfen.75",
    ],
  },
  {
    id: "provisional-answer",
    name: "Leave Room for an Answer",
    colors: ["tide", "ember"] as ManaColor[],
    sets: ["unfinished-answer", "saltwind"],
    plan: "Develop Spellcraft, hold a counter or damage spell and recover a traded attacker. Force two threats through the same held response.",
    basics: ["unfinished-answer.20", "unfinished-answer.22"],
    choices: [
      "unfinished-answer.1",
      "unfinished-answer.2",
      "unfinished-answer.7",
      "unfinished-answer.8",
      "unfinished-answer.13",
      "unfinished-answer.14",
      "unfinished-answer.3",
      "unfinished-answer.4",
      "unfinished-answer.5",
      "unfinished-answer.9",
      "unfinished-answer.10",
      "unfinished-answer.15",
      "saltwind.13",
      "saltwind.66",
      "saltwind.4",
    ],
  },
];

export const livingRecipeDeck = (id: string): string[] | undefined => {
  const p = livingRecipes.find((p) => p.id === id);
  return (
    p && [
      ...p.basics.flatMap((id) => Array<string>(20).fill(id)),
      ...p.choices.flatMap((id) => Array<string>(4).fill(id)),
    ]
  );
};
