import {
  C,
  S,
  P,
  R,
  H,
  culture,
  rare,
  type LivingEntry,
} from "./living-expansion-tools";

/** Collector numbers 25–80: accountable observation, renewal and incomplete records. */
export const unfinishedAnswerExpansion: LivingEntry[] = [
  ...culture("Star", [
    C(
      "Groundline Observation Hand",
      "tide",
      1,
      1,
      3,
      "A human observation worker kneels beside a ground-level measuring cord, holding its brass weight steady beneath a dark velvet awning.",
      { keywords: ["rootfast"] },
    ),
    C(
      "Late-reading Courier",
      "ember",
      2,
      2,
      2,
      "A human courier hurries down an observatory stair with a closed instrument case and a newly folded reading cloth.",
      { keywords: ["haste"] },
    ),
    C(
      "Uncertain-angle Observer",
      "tide",
      3,
      2,
      4,
      "A human observer adjusts a modest brass sighting frame while two different shadow lines remain visible on the stone below.",
      { trigger: "spellcraft" },
    ),
    C(
      "Signal-screen Attendant",
      "ember",
      4,
      4,
      3,
      "A human attendant turns a shielded signal lamp toward a distant observation station, keeping the bright beam clear of nearby households.",
      { effect: "damage", amount: 1 },
    ),
    S(
      "Challenge the Perfect Reading",
      "Instant",
      "tide",
      2,
      "counter",
      1,
      "A collector's blue arc from a small brass sight breaks an overconfident magical diagram before it closes into a seal.",
    ),
    S(
      "Focus the Warning Beam",
      "Sorcery",
      "ember",
      3,
      "damage",
      4,
      "An invented amber beam passes through a practical shuttered lamp toward a threatening magical shape beyond the observation terrace.",
    ),
    P(
      "Portable Meridian Frame",
      "Artifact",
      "tide",
      2,
      "mana-rock",
      "A compact brass sighting frame folds over a velvet-lined wooden case beside a weighted cord and a worn observation stool.",
    ),
    C(
      "Second-angle Apprentice",
      "tide",
      2,
      2,
      2,
      "A human apprentice takes a second sight from a low terrace, keeping one eye at a brass frame while the first observer's station stays separate.",
      { trigger: "spellcraft" },
    ),
    C(
      "Storm-warning Runner",
      "ember",
      3,
      3,
      3,
      "A human runner carries a covered amber warning lamp across a rain-dark terrace, a strapped instrument case bouncing at her side.",
      { keywords: ["haste"] },
    ),
    C(
      "Household Cost Recorder",
      "tide",
      4,
      3,
      4,
      "A human recorder sets food baskets and worn work tokens beside an expensive observation instrument, making the supporting households' cost visible.",
      { effect: "draw", amount: 1 },
    ),
    S(
      "Interrupt the False Signal",
      "Instant",
      "ember",
      2,
      "damage",
      3,
      "A collector's focused amber flash cuts across a misleading magical signal above a dark observation court, with the source lamp clearly visible.",
    ),
    S(
      "Compare the Clouded Nights",
      "Sorcery",
      "tide",
      3,
      "draw",
      2,
      "Two unlettered observation cloths and a rain-stained brass instrument lie under one lamp, preserving nights when the sky revealed little.",
    ),
    P(
      "The Station's Warning Light",
      "Enchantment",
      "ember",
      3,
      "watchfire",
      "A restrained amber glow pulses between shuttered terrace lamps above ordinary sleeping households, with no restored ancient network.",
    ),
    C(
      "Velvet Cross-check Warden",
      "tide",
      5,
      4,
      6,
      "An unnamed human warden stands beside two separate sighting frames with a long practical signal pole, protecting the work without claiming a final answer.",
      { keywords: ["reach"], trigger: "spellcraft" },
    ),
    S(
      "Keep the Contradictory Reading",
      "Instant",
      "tide",
      3,
      "draw",
      2,
      "A human hand catches a discarded observation cloth in a sudden blue lamplight and places it beside the favored result.",
    ),
    P(
      "Cabinet of Unsettled Angles",
      "Artifact",
      "tide",
      4,
      "archive",
      "A shallow velvet-lined cabinet holds misaligned brass sights and separate unfinished observation rolls, each kept rather than polished into agreement.",
    ),
  ]),
  ...culture("Flame", [
    C(
      "Firebreak Message Runner",
      "ember",
      1,
      2,
      1,
      "A living human gardener runs along a low cleared firebreak with a closed seed jar, smoked-orange sleeves and sulfur-green straps visible.",
      { keywords: ["haste"] },
    ),
    C(
      "Seed-house Welcome Keeper",
      "tide",
      2,
      2,
      3,
      "A human seed keeper opens a cool ceramic-screened store room to arriving garden households, plain seed jars stacked safely behind her.",
      { trigger: "welcome" },
    ),
    C(
      "Surviving-bed Gardener",
      "ember",
      3,
      3,
      3,
      "A human gardener waters a small living bed behind an ash-white ceramic windscreen while burnt ground remains visible beyond the low firebreak.",
      { effect: "heal", amount: 2 },
    ),
    C(
      "Kiln-yard Screen Mover",
      "ember",
      4,
      4,
      4,
      "A living human kiln worker pushes a heavy ceramic screen on a practical sled, orange work clothes dusty and green carrying straps taut.",
      { keywords: ["trample"] },
    ),
    S(
      "Douse the Escaping Spark",
      "Instant",
      "ember",
      1,
      "damage",
      2,
      "A collector's brief controlled orange spell catches an escaping spark against an ash-white fire screen before it reaches the garden.",
    ),
    S(
      "Defend the Resident Gardens",
      "Sorcery",
      "ember",
      3,
      "rally",
      1,
      "Human resident gardeners raise shovels and water vessels behind low firebreaks while a traveling teacher's distant banner remains separate.",
    ),
    P(
      "Kiln-side Water Treadle",
      "Artifact",
      "ember",
      2,
      "mana-rock",
      "A simple wooden foot treadle raises water beside a working kiln, with clay pipes and a low ceramic screen protecting the seed house.",
    ),
    C(
      "Trial-bed Firekeeper",
      "ember",
      2,
      2,
      3,
      "A human worker tends a tightly bounded test bed beside water jars, a low ceramic barrier keeping the experiment apart from household gardens.",
      { trigger: "spellcraft" },
    ),
    C(
      "Failed-season Seed Recorder",
      "tide",
      3,
      2,
      4,
      "A human recorder compares a sparse seed tray with a full older jar beneath an ash-white screen, preserving the season's disappointing result.",
      { effect: "draw", amount: 1 },
    ),
    C(
      "Emberbreak Rescue Gardener",
      "ember",
      4,
      4,
      3,
      "A living human gardener strides through a safe gap in a firebreak carrying a rescued seed tray and a clean water flask, no burning body or elemental form.",
      { keywords: ["haste", "lifelink"] },
    ),
    S(
      "Rest the Kiln Watch",
      "Instant",
      "tide",
      2,
      "renew",
      1,
      "A rested human worker accepts the kiln watch's water ladle as imagined cool light loosens the tired keeper's green shoulder straps.",
    ),
    S(
      "Contain the Reckless Burning",
      "Sorcery",
      "ember",
      4,
      "damage",
      5,
      "An invented focused orange strike drives a dangerous magical blaze into a cleared test bed surrounded by ceramic screens and water jars.",
    ),
    P(
      "Seed for the Next Household",
      "Enchantment",
      "tide",
      3,
      "welcome",
      "A quiet blue-green glow passes among separate seed jars offered across a garden threshold, with resident households keeping their own supplies.",
    ),
    C(
      "Convocation Firebreak Warden",
      "ember",
      5,
      5,
      5,
      "An unnamed living human warden in smoked-orange work clothes advances along a cleared firebreak with a heavy shovel and a strapped water vessel.",
      { keywords: ["trample", "haste"] },
    ),
    S(
      "Answer the Spreading Flame",
      "Instant",
      "ember",
      4,
      "damage",
      5,
      "A collector's sharp orange intervention rises from a gardener's practical fire shovel toward a spreading magical flame beyond the last ceramic screen.",
    ),
    P(
      "The Guarded Kiln Beacon",
      "Artifact",
      "ember",
      4,
      "watchfire",
      "A small controlled kiln beacon burns inside a tall ash-white ceramic cage, water jars close by and living garden rows safely beyond a firebreak.",
    ),
  ]),
  ...culture("Rune", [
    C(
      "Interrupted-stripe Copyist",
      "tide",
      1,
      1,
      2,
      "A human copyist with a broken cinnabar sleeve stripe opens a weathered document case beneath a low slab roof, preserving the gap in a copied account.",
      { trigger: "recordwork" },
    ),
    C(
      "Sealed-door Supply Hand",
      "ember",
      2,
      2,
      2,
      "A human supply worker braces a grain basket beside a still-sealed archive door, parchment-grey coat and interrupted red strap visible.",
      { keywords: ["rootfast"] },
    ),
    C(
      "Precautionary Screen Keeper",
      "tide",
      3,
      2,
      4,
      "A human custodian positions a plain weathered-lead screen between an uncertain workroom and waiting supply households.",
      { effect: "shield", amount: 2 },
    ),
    C(
      "Slab-roof Signal Guard",
      "ember",
      4,
      3,
      5,
      "A human guard stands on a low archive roof with a long hooked signal pole, keeping a practical watch above closed document cases.",
      { keywords: ["reach"] },
    ),
    S(
      "Pause at the Broken Stripe",
      "Instant",
      "tide",
      2,
      "bind",
      1,
      "An imagined blue band halts a hurried visitor at an interrupted cinnabar threshold stripe before a disputed sealed work.",
    ),
    S(
      "Preserve the Failed Trial",
      "Sorcery",
      "tide",
      4,
      "draw",
      3,
      "Human hands set a scorched test fragment beside three separate unlettered records under a slab-roof lamp, keeping failure visible.",
    ),
    P(
      "Archive Door Counterweight",
      "Artifact",
      "tide",
      2,
      "mana-rock",
      "A weathered lead counterweight hangs in a simple timber archive-door frame beside a closed document case and a broken cinnabar stripe.",
    ),
    C(
      "Provisional Trial Attendant",
      "tide",
      2,
      2,
      3,
      "A human attendant watches a small bounded test from behind a plain screen, one hand on a document case and the other ready at a stop cord.",
      { trigger: "spellcraft" },
    ),
    C(
      "Missing-record Mourner",
      "ember",
      3,
      3,
      3,
      "A human custodian places an empty damaged document case on a low archive shelf, leaving its gap beside surviving records rather than filling it.",
      { trigger: "mourning" },
    ),
    C(
      "Repair-case Examiner",
      "tide",
      4,
      3,
      5,
      "A human examiner compares a repaired lead-lined case with its loose broken hinge beneath an archive station's low slab roof.",
      { trigger: "recordwork" },
    ),
    S(
      "Lower the Household Screen",
      "Instant",
      "tide",
      2,
      "shield",
      5,
      "A collector's cool blue light fills a lowered practical safety screen between an uncertain archive experiment and a household's warm doorway.",
    ),
    S(
      "Reclaim the Experiment's Cost",
      "Sorcery",
      "ember",
      4,
      "drain",
      4,
      "An imagined ember-colored thread carries light from a costly sealed experiment back toward plain grain bowls on a supply table.",
    ),
    P(
      "A Record of What Remains",
      "Enchantment",
      "tide",
      3,
      "archive",
      "Soft blue light picks out preserved gaps between weathered cases in a low archive room, with incomplete fragments left visibly incomplete.",
    ),
    C(
      "Margin Stop-cord Warden",
      "ember",
      5,
      4,
      5,
      "An unnamed human warden pulls a practical stop cord beside a screened trial, a controlled imagined flash striking the dangerous spell beyond the barrier.",
      { effect: "damage", amount: 3, trigger: "spellcraft" },
    ),
    S(
      "Open the Unfavored Case",
      "Instant",
      "tide",
      4,
      "draw",
      3,
      "A human hand lifts a weathered lead case into sudden blue lamplight, revealing preserved contradictory fragments without readable writing.",
    ),
    P(
      "The Case Returned for Repair",
      "Artifact",
      "tide",
      4,
      "recordwork",
      "A carefully patched lead-lined document case stands open beside its retained broken hinge, a spool of plain cord and interrupted cinnabar markings.",
    ),
  ]),
  R(
    "Sheltered Seed Terrace",
    "ember",
    ["ember"],
    "common",
    "Living seed beds glow beside a small safely screened kiln on an ash-country terrace, with low firebreaks and clean water jars.",
  ),
  R(
    "Rain-cooled Trial Court",
    "tide",
    ["tide", "ember"],
    "uncommon",
    "A small outdoor trial court holds shallow rain channels beside a shuttered furnace, with a closed waiting gate between the two work areas.",
  ),
  R(
    "Observatory Dawn Landing",
    "tide",
    ["tide", "dawn"],
    "rare",
    "A modest observation landing catches the first dawn beside a rain basin, brass sighting frame and carefully folded cloth.",
  ),
  R(
    "Rootbound Kiln Garden",
    "ember",
    ["ember", "grove"],
    "rare",
    "A low screened kiln stands beside thriving root beds and a simple irrigation channel, showing patient cultivation after a difficult season.",
  ),
  rare(
    P(
      "The Accountable Worktable",
      "Artifact",
      "ember",
      4,
      "anthem",
      "An invented collector comparison places separate observation frames, seed jars and archive cases on a sturdy shared worktable without inventing a united institution.",
    ),
  ),
  rare(
    S(
      "Leave the Answer Unfinished",
      "Sorcery",
      "tide",
      5,
      "draw",
      4,
      "A collector's imagined blue light reveals several incomplete records, a failed seed tray and a misaligned brass sight, preserving the spaces where certainty is absent.",
    ),
  ),
  H(
    "Keeper of the Surviving Beds",
    "ember",
    5,
    4,
    [
      [1, "heal", 2],
      [-2, "damage", 3],
      [-6, "rally", 2],
    ],
    "An invented living human Emberwake keeper carries a surviving seed tray beside a cleared firebreak, smoked-orange coat and green straps dusty from ordinary work.",
  ),
  H(
    "Custodian of the Open Question",
    "tide",
    5,
    4,
    [
      [1, "shield", 2],
      [-2, "draw", 2],
      [-7, "rally", 3],
    ],
    "An invented human Margin custodian sets a sealed case beside an open incomplete record while supporting households wait under the slab roof; no lost mechanism is restored.",
  ),
];
