import { z } from 'zod';
import { pngDimensions, readArtFile } from '../toolchain/process';
import { fetchJson, storeCandidate, validateRequest } from './shared';
import type { ArtGenerationRequest, ArtGenerator, GeneratedCandidate, ProviderCapabilities } from './types';

/** Official API v2 Pixflux contract, checked 2026-09-05; endpoint is deliberately fixed. */
export class PixelLabGenerator implements ArtGenerator {
  readonly id = 'pixellab';
  constructor(private options: { env?: NodeJS.ProcessEnv; timeoutMs?: number } = {}) {}
  capabilities(): ProviderCapabilities { return { autonomous: true, references: true, seeded: true, animation: false, maxWidth: 400, maxHeight: 400, limitations: ['This adapter implements still-image Pixflux, not the separate character/animation/hex APIs. One reference is an init image, not a guaranteed identity lock. No-background above 200×200 is a blank background, not guaranteed alpha.'] }; }
  async generate(request: ArtGenerationRequest): Promise<GeneratedCandidate[]> {
    const checked = await validateRequest(request), key = (this.options.env ?? process.env).PIXELLAB_API_KEY;
    if (!key?.trim()) throw new Error('PIXELLAB_API_KEY is missing. No generation request was sent.');
    if (checked.width < 16 || checked.height < 16 || checked.width > 400 || checked.height > 400 || checked.width * checked.height < 1024 || (checked.references?.length ?? 0) > 1) throw new Error('Pixflux supports dimensions 16–400, area at least 32×32, and at most one init-image reference in this adapter.');
    const seed = checked.seed === undefined ? undefined : Number(checked.seed); if (seed !== undefined && !Number.isSafeInteger(seed)) throw new Error('PixelLab seed exceeds the safe integer range.');
    const reference = checked.references?.[0], referenceData = reference ? await readArtFile(reference.path) : undefined;
    if (referenceData) pngDimensions(referenceData);
    const body = { description: checked.prompt, image_size: { width: checked.width, height: checked.height }, no_background: true, ...(seed === undefined ? {} : { seed }), ...(referenceData ? { init_image: { type: 'base64', base64: referenceData.toString('base64') } } : {}) };
    const response = z.object({ image: z.object({ base64: z.string().min(1).max(85_000_000) }) }).parse(await fetchJson('https://api.pixellab.ai/v2/create-image-pixflux', { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${key}` }, body: JSON.stringify(body) }, this.options.timeoutMs));
    const encoded = response.image.base64.replace(/^data:image\/png;base64,/, ''); if (!/^[a-zA-Z0-9+/]+={0,2}$/.test(encoded)) throw new Error('PixelLab returned invalid base64 PNG data.');
    const bytes = Buffer.from(encoded, 'base64'), size = pngDimensions(bytes);
    if (size.width !== checked.width || size.height !== checked.height) throw new Error('PixelLab returned different dimensions; candidate was not accepted.');
    return [await storeCandidate(checked, this.id, [bytes], { model: 'pixflux-api-v2', seed: checked.seed, licenseNotes: ['Generated by PixelLab under the operator account terms. Review current commercial-use and reference rights before approval; API availability is not a license grant.'] })];
  }
}
